# Generated by Django 5.2.5 on 2025-08-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_image_project_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.AddField(
            model_name='project',
            name='image_path',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
