# Generated by Django 5.2.5 on 2025-08-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_image_url_project_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image_path',
            new_name='image_url',
        ),
    ]
